THEORETICAL QUESTIONS

1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

ANS. numpy deals with large amounts of data, offering significant improvement in speed and memory as it uses a type data structure. Also, numpy offers high-level syntax and a wide range of numerical operation

Numpy serves uses to solves complex algorithms in the field of probability and statistical analysis

2.Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the 
other

ans. as np. mean() is used to calculate the average values in an array 
        np. average() gives weight to the average of the values in an array.

when we want unweighted average of data for our computation we use np.mean()
when we want weighted avaerage number for our calculation we use np.average()?

In [1]:
#3.Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D 
#array.

#ans. 
import numpy as np
arr1=np.random.randint(1,6,size=(3,3))
arr1

array([[4, 5, 5],
       [4, 1, 1],
       [1, 3, 1]], dtype=int32)

In [3]:
arr2=np.array([1,2,3,4,5,6])

In [37]:
arr1[::-1]

array([[5, 3, 2],
       [5, 4, 2],
       [4, 3, 1]], dtype=int32)

In [39]:
arr2[::-1]

array([6, 5, 4, 3, 2, 1])

In [47]:
arr2.ndim

1

In [61]:
 #4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
arr1

array([[4, 3, 1],
       [5, 4, 2],
       [5, 3, 2]], dtype=int32)

In [67]:
arr1.dtype


dtype('int32')

for memory managment if we use int32 in place of int64 it will consume less memory , and if we use float 32 inplace of float64 it wil run faster as it consum less CPU power 

5.Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

An ndarray, or N-dimensional array, is a central feature of NumPy that stores homogeneous data types, meaning all elements in the array must be of the same type. Unlike standard Python lists, which can store any kind of data, ndarrays support multiple dimensions, allowing for the representation of complex data structures. 

Key features of ndarrays include:
- Support for vectorized operations, enabling efficient mathematical computations on large datasets.
- A rich set of mathematical functions that cater to linear algebra, statistics, and random sampling.

In comparison to standard Python lists, ndarrays are generally faster and more efficient in terms of memory consumption. While lists can store various data types, this flexibility comes at the cost of speed and increased memory usage.


 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

ans.NumPy Arrays: Offer a vast array of built-in functions for complex mathematical operations (like linear algebra, Fourier transforms).
Python Lists: Lack these built-in capabilities and require additional coding or libraries to achieve similar functionality.

NumPy Arrays: Store data in contiguous blocks of memory, leading to better  performance and less memory
Python Lists: Store references to objects, which means more memory usage and less efficient


In [70]:
 #7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

#ans. vstack() used for stacking arrays top of one each other
#     hstack() used for horizontally stacking array

     

arr1 = np.array([1, 2, 3]) 
arr2 = np.array([4, 5, 6])

np.vstack((arr1,arr2))


array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

#8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various 
#array dimensions.

fliplr()
Flips the array in the left/right direction.
Reverses the order of columns.
Works on arrays of 2 or more dimensions.

flipud()
Flips the array in the up/down direction.
Reverses the order of rows.
Works on arrays of 2 or more dimensions.

In [88]:
arr1=np.array([[1,2,3],[4,5,6]])
np.fliplr(arr1)
#np.fliplr(arr1)

array([[3, 2, 1],
       [6, 5, 4]])

In [92]:
np.flipud(arr1)

array([[4, 5, 6],
       [1, 2, 3]])

 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

this method in NumPy that allows us to split an array into multiple sub-arrays.

In [102]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
new_arr = np.array_split(arr_2d, 3, axis=0) 
print(new_arr)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [110]:
#for un even data type
arr = np.array([1, 2, 3, 4, 5, 6,7]) 
arr2 = np.array_split(arr, 3) 
print(arr2)



[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [112]:
arr = np.array([1, 2, 3, 4, 5, 6, 7]) 
arr3 = np.array_split(arr, 3) 
print(arr3)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Broadcasting allows NumPy to perform operations on arrays of different shapes by automatically expanding their dimensions to make them compatible

Vectorization refers to the ability of NumPy to apply operations to entire arrays at once, without the need for explicit loops.

In [116]:
arr_2d+5 #vectorized

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [120]:
arr_2d.reshape(1,9) #broadcasting

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

In [9]:
arr4=np.random.randint(1,100,size= (3,3))
arr4

array([[87, 67, 40],
       [42, 16, 96],
       [27, 52, 70]], dtype=int32)

In [11]:
arr4.T


array([[87, 42, 27],
       [67, 16, 52],
       [40, 96, 70]], dtype=int32)

2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [17]:
arr2=np.array([1,2,3,4,5,6,7,8,9,10])
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr2.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [23]:
arr2.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [47]:
arr=np.random.rand(4,4)
arr

array([[0.03216627, 0.17577448, 0.80801288, 0.19077265],
       [0.81650642, 0.97222042, 0.15409688, 0.27559471],
       [0.99509236, 0.58503415, 0.54225207, 0.91549061],
       [0.89614326, 0.12795522, 0.8437099 , 0.0778894 ]])

In [49]:

inner_array = np.random.rand(4, 4)

bordered_array = np.zeros((6, 6))

bordered_array[1:5, 1:5] = inner_array

print(inner_array)
print(bordered_array)

[[0.57497344 0.77909969 0.16535932 0.06625076]
 [0.50934851 0.47447744 0.26679778 0.392757  ]
 [0.93913191 0.12717525 0.86984103 0.54386542]
 [0.56275774 0.4260786  0.25461256 0.10276333]]
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.57497344 0.77909969 0.16535932 0.06625076 0.        ]
 [0.         0.50934851 0.47447744 0.26679778 0.392757   0.        ]
 [0.         0.93913191 0.12717525 0.86984103 0.54386542 0.        ]
 [0.         0.56275774 0.4260786  0.25461256 0.10276333 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [51]:
np.arange(10,60,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations 
(uppercase, lowercase, title case, etc.) to each element.

In [61]:
l="python,numpy,pandas"
l.split(",")
arr=np.array(l.split(","))
arr

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [63]:
np.char.upper(arr)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [65]:
np.char.capitalize(arr)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [67]:
np.char.title(arr)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

 6. Generate a NumPy array of words. Insert a space between each character of every word in the array

In [75]:
arr=np.array(["pwskill","data","atreya"])
arr

array(['pwskill', 'data', 'atreya'], dtype='<U7')

In [79]:
np.char.join(" ",arr)

array(['p w s k i l l', 'd a t a', 'a t r e y a'], dtype='<U13')

7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [81]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
arr+5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [85]:
arr-5

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [87]:
arr/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [89]:
arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [93]:
arr=np.eye(5,5) 
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [105]:
arr_1=arr[0:5][0:1]
arr_1

array([[1., 0., 0., 0., 0.]])

 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in 
this array.

In [197]:
arr=np.random.randint(0,100,size=(3,3))
arr

array([[48, 75, 43],
       [28, 70, 40],
       [13,  7, 93]], dtype=int32)

In [205]:
def prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqr(num)) + 1):
        if num % i == 0:
            return False
    return True
prime_flags = np.vectorize(prime)(arr)

arr[prime_flags]

#print("Prime numbers in the array:",arr[prime_flags] )


array([], dtype=int32)

10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly 
averages.

In [211]:

arr=np.random.randint(29,43,size=(4,7))
arr

array([[35, 29, 33, 39, 38, 31, 34],
       [42, 33, 41, 40, 31, 33, 42],
       [39, 33, 35, 30, 39, 32, 40],
       [30, 41, 33, 31, 42, 33, 38]], dtype=int32)

In [235]:
arr2=arr[0:8][0:1]

In [239]:
average_temp=np.average(arr2)
print("average temperature of this week is",average_temp )

average temperature of this week is 34.142857142857146
