THEORETICAL QUESTIONS

1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

ANS. numpy deals with large amounts of data, offering significant improvement in speed and memory as it uses a type data structure. Also, numpy offers high-level syntax and a wide range of numerical operation

Numpy serves uses to solves complex algorithms in the field of probability and statistical analysis

2.Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the 
other

ans. as np. mean() is used to calculate the average values in an array 
        np. average() gives weight to the average of the values in an array.

when we want unweighted average of data for our computation we use np.mean()
when we want weighted avaerage number for our calculation we use np.average()?

In [21]:
#3.Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D 
#array.

#ans. 
import numpy as np
arr1=np.random.randint(1,6,size=(3,3))
arr1

array([[4, 3, 1],
       [5, 4, 2],
       [5, 3, 2]], dtype=int32)

In [35]:
arr2=np.array([1,2,3,4,5,6])

In [37]:
arr1[::-1]

array([[5, 3, 2],
       [5, 4, 2],
       [4, 3, 1]], dtype=int32)

In [39]:
arr2[::-1]

array([6, 5, 4, 3, 2, 1])

In [47]:
arr2.ndim

1

In [61]:
 #4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
arr1

array([[4, 3, 1],
       [5, 4, 2],
       [5, 3, 2]], dtype=int32)

In [67]:
arr1.dtype


dtype('int32')

for memory managment if we use int32 in place of int64 it will consume less memory , and if we use float 32 inplace of float64 it wil run faster as it consum less CPU power 

5.Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

An ndarray, or N-dimensional array, is a central feature of NumPy that stores homogeneous data types, meaning all elements in the array must be of the same type. Unlike standard Python lists, which can store any kind of data, ndarrays support multiple dimensions, allowing for the representation of complex data structures. 

Key features of ndarrays include:
- Support for vectorized operations, enabling efficient mathematical computations on large datasets.
- A rich set of mathematical functions that cater to linear algebra, statistics, and random sampling.

In comparison to standard Python lists, ndarrays are generally faster and more efficient in terms of memory consumption. While lists can store various data types, this flexibility comes at the cost of speed and increased memory usage.


 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

ans.NumPy Arrays: Offer a vast array of built-in functions for complex mathematical operations (like linear algebra, Fourier transforms).
Python Lists: Lack these built-in capabilities and require additional coding or libraries to achieve similar functionality.

NumPy Arrays: Store data in contiguous blocks of memory, leading to better  performance and less memory
Python Lists: Store references to objects, which means more memory usage and less efficient


In [70]:
 #7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

#ans. vstack() used for stacking arrays top of one each other
#     hstack() used for horizontally stacking array

     

arr1 = np.array([1, 2, 3]) 
arr2 = np.array([4, 5, 6])

np.vstack((arr1,arr2))


array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

#8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various 
#array dimensions.

fliplr()
Flips the array in the left/right direction.
Reverses the order of columns.
Works on arrays of 2 or more dimensions.

flipud()
Flips the array in the up/down direction.
Reverses the order of rows.
Works on arrays of 2 or more dimensions.

In [88]:
arr1=np.array([[1,2,3],[4,5,6]])
np.fliplr(arr1)
#np.fliplr(arr1)

array([[3, 2, 1],
       [6, 5, 4]])

In [92]:
np.flipud(arr1)

array([[4, 5, 6],
       [1, 2, 3]])

 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

this method in NumPy that allows us to split an array into multiple sub-arrays.

In [102]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
new_arr = np.array_split(arr_2d, 3, axis=0) 
print(new_arr)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [110]:
#for un even data type
arr = np.array([1, 2, 3, 4, 5, 6,7]) 
arr2 = np.array_split(arr, 3) 
print(arr2)



[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [112]:
arr = np.array([1, 2, 3, 4, 5, 6, 7]) 
arr3 = np.array_split(arr, 3) 
print(arr3)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Broadcasting allows NumPy to perform operations on arrays of different shapes by automatically expanding their dimensions to make them compatible

Vectorization refers to the ability of NumPy to apply operations to entire arrays at once, without the need for explicit loops.

In [116]:
arr_2d+5 #vectorized

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [120]:
arr_2d.reshape(1,9) #broadcasting

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])